### ISSUE TITLE
Boxtron ignores / overrides various options

### ISSUE THREAD

**Issue by qptain-Nemo** [dreamer/boxtron#44]
I can't seem to be able to disable aspect correction or change the sound sample rate. Setting the corresponding options to desired values in both the "original" windows config file for the game and the boxtron_gameid_hash.conf has no effect, boxtron_auto.conf always ends up containing aspect=true.

**Comment by dreamer** [comment]
https://github.com/dreamer/boxtron/wiki/Configuration#user-conf-file

You can change aspect or any other dosbox setting in user .conf file (the one named `boxtron_<appid>_<hash>.conf`). It won't affect `boxtron_auto.conf` - this file is *always* generated anew based on the game files, runtime state of your OS, your env variables, etc.

Boxtron passes both "auto" and "user" conf files to DOSBox, "user" file overrides options in "auto" file.

Hope this helps :)

Out of curiosity: which DOS game on Steam has an incorrect aspect ratio setting? (whenever I find one, I put a tweak in Boxtron database).

**Comment by qptain-Nemo** [comment]
Oh, my mistake. I was fighting blurry linear filtering, I thought it was caused by aspect ratio still being on, I didn't realize you have to set the output to openglnb to disable it. So the passing of option does work. This issue is inaccurate, my apologies. Feel free to close and/or delete it.

The game I'm currently dealing with is Timequest (https://store.steampowered.com/app/1297560/Timequest/). It natively runs at 640x350 but the provided configs force multiples of 640x480 on it with aspect ratio on (and bilinear filtering), which looks terrible to me.

**Comment by dreamer** [comment]
Oh, if you want to avoid blurriness then there are even better options :) (`openglnb` will remove bilinear filtering, but might cause pixel-doubling in some lines, which makes the ascii art look unnatural)

1. Install [DOSBox Staging](https://dosbox-staging.github.io/) and configure it instead of old DOSBox.
2. In your user conf file put:

```
[sdl]
output = opengl

[render]
scaler = none
glshader = sharp
```
This will turn on sharp-bilinear scaling, which will look like this on 1080p screen (the game is "Spellcasting 101" - zoom in to see if it's sharp enough):

![Screenshot from 2020-11-29 00-05-23](https://user-images.githubusercontent.com/3967/100527869-0239bc80-31d7-11eb-835d-ce4521d1df0c.png)

Or you can turn on integer scaling this way, which works quite well for these titles:

```
[sdl]
output = texturepp

[render]
scaler = none # does not affect texturepp
glshader = none # does not affect texturepp
```
Which will try to maximize scaling while making image distortion as small as possible, on 1080p for Spellcasting 101 it looks like this (on zoom-in you will notice 0 blurriness, but there are black borders on top and bottom now):
![Screenshot from 2020-11-29 00-06-17](https://user-images.githubusercontent.com/3967/100527927-6fe5e880-31d7-11eb-9af1-1c9032e2984e.png)

(These options will work only with dosbox staging; the easiest way to install dosbox-staging right now seems to be unpacking tarball somewhere and updating this boxtron preference: https://github.com/dreamer/boxtron/wiki/Configuration#dosboxcmd)

Anyway - have fun :)

**Comment by qptain-Nemo** [comment]
Thanks a lot for the info!
